### PR TITLE
mm/alloc: acquire `Slab` spinlock when freeing a pointer

### LINKED ISSUE #107: mm/alloc: undefined behavior in `SvsmAllocator::dealloc()`
[Miri](/rust-lang/miri) reports undefined behavior when running the `mm::alloc::test_slab_alloc_free_many` test:

```console
$ MIRIFLAGS="-Zmiri-permissive-provenance" cargo +nightly miri test --target=x86_64-unknown-linux-gnu test_slab_alloc_free_many
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running unittests src/lib.rs (target/miri/x86_64-unknown-linux-gnu/debug/deps/svsm-4dadd712fd0a3e32)

running 1 test
test mm::alloc::test_slab_alloc_free_many ... error: Undefined Behavior: trying to retag from <wildcard> for SharedReadWrite permission at alloc174[0x0], but no exposed tags have suitable permission in the borrow stack for this location
    --> src/mm/alloc.rs:1276:17
     |
1276 |                 (*slab).deallocate(virt_addr);
     |                 ^^^^^^^
     |                 |
     |                 trying to retag from <wildcard> for SharedReadWrite permission at alloc174[0x0], but no exposed tags have suitable permission in the borrow stack for this location
     |                 this error occurs as part of two-phase retag at alloc174[0x0..0x40]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
     = note: BACKTRACE:
     = note: inside `<mm::alloc::SvsmAllocator as core::alloc::GlobalAlloc>::dealloc` at src/mm/alloc.rs:1276:17: 1276:24
note: inside `mm::alloc::test_slab_alloc_free_many`
    --> src/mm/alloc.rs:1569:26
     |
1569 |                 unsafe { ALLOCATOR.dealloc(*p, layout) };
     |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside closure
    --> src/mm/alloc.rs:1539:32
     |
1537 | #[test]
     | ------- in this procedural macro expansion
1538 | // Allocate and free a couple of objects for each slab size.
1539 | fn test_slab_alloc_free_many() {
     |                                ^
     = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error

error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/home/carlos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri runner /home/carlos/dev/svsm-gh/target/miri/x86_64-unknown-linux-gnu/debug/deps/svsm-4dadd712fd0a3e32 test_slab_alloc_free_many` (exit status: 1)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
```

### PR DESCRIPTION
**Pull request by 00xc**
Fix the undefined behavior detailed in #107 by acquiring a lock to the corresponding `Slab` before freeing an allocation from it. Before, this could lead to undefined behavior, as freeing an address would access the Slab mutably, regardless of any concurrent users.

The appropriate `Slab` can be found by using the `layout` parameter to `SvsmAllocator::dealloc()`.

The PR also includes small refactors and cleanups to make the change simpler.

This does not completely solve #107 because by avoiding this UB, further UB warnings are revealed.

### CODE REVIEW

File: src/mm/alloc.rs [hunk 1]
```diff
@@ -1219,61 +1219,64 @@ impl SvsmAllocator {
...
             }
-            Page::SlabPage(si) => {
-                assert!(!si.slab.is_null());
-                let slab = si.slab.as_mut_ptr::<Slab>();
-
-                (*slab).deallocate(virt_addr);
+            Page::SlabPage(_si) => {
+                let Some(slab) = self.get_slab(size) else {
+                    panic!("Invalid page info");
+                };
```
Comment (Freax13) [inline src/mm/alloc.rs:1278]:
```suggestion
                let slab = self.get_slab(size).expect("Invalid page info");
```

File: src/mm/alloc.rs [hunk 2]
```diff
@@ -1219,61 +1219,64 @@ impl SvsmAllocator {
...
 
         let result = ROOT_MEM.lock().get_page_info(virt_addr);
-
-        if result.is_err() {
+        let Ok(info) = result else {
             panic!("Freeing unknown memory");
-        }
-
-        let info = result.unwrap();
+        };
```
Comment (Freax13) [inline src/mm/alloc.rs:1269]: This can be shortened to:
```rust
        let info = result.expect("Freeing unknown memory");
```

**Comment by Freax13** [comment]
> This does not completely solve #107 because by avoiding this UB, further UB warnings are revealed.

Are you planning on investigating those? If not, I'd like to do that.

**Comment by 00xc** [comment]
> > This does not completely solve #107 because by avoiding this UB, further UB warnings are revealed.
> 
> Are you planning on investigating those? If not, I'd like to do that.

I was planning on perhaps taking a look next week, but if you have the time and the will please do.

**Comment by joergroedel** [comment]
LGTM, the SLAB_PAGE_SLAB is called directly, so no need to free into it from the generic allocator.

While at it, can you please also update the allocation path for slab pages (and SlabPageInfo) to not store a pointer to the slab anymore?

**Comment by joergroedel** [comment]
Thanks, but this still has the encoding part partially in the `allocate_slab_page()` path. The `slab` argument can be removed from this call-path.

**Comment by joergroedel** [comment]
Looks good now, thanks!
